export const adminActionTypes = {
  ADMIN_LOGIN_REQUEST: "ADMIN_LOGIN_REQUEST",
  ADMIN_LOGIN_SUCCESS: "ADMIN_LOGIN_SUCCESS",
  ADMIN_LOGIN_FAILED: "ADMIN_LOGIN_FAILED",

  ADMIN_LOGOUT: "ADMIN_LOGOUT",

  HOME_REQUEST: "HOME_REQUEST",
  HOME_SUCCESS: "HOME_SUCCESS",
  HOME_FAILED: "HOME_FAILED",

  ADMIN_USER_BLOCK_REQUEST: "ADMIN_USER_BLOCK_REQUEST",
  ADMIN_USER_BLOCK_SUCCESS: "ADMIN_USER_BLOCK_SUCCESS",
  ADMIN_USER_BLOCK_FAILED: "ADMIN_USER_BLOCK_FAILED",

  ADMIN_USER_SEARCH_REQUEST: "ADMIN_USER_SEARCH_REQUEST",
  ADMIN_USER_SEARCH_SUCCESS: "ADMIN_USER_SEARCH_SUCCESS",
  ADMIN_USER_SEARCH_FAILED: "ADMIN_USER_SEARCH_FAILED",
};
