export const userActionTypes = {
  USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAILED: "USER_LOGIN_FAILED",

  USER_LOGOUT: "USER_LOGOUT",

  USER_SIGNUP_REQUEST: "USER_SIGNUP_REQUEST",
  USER_SIGNUP_SUCCESS: "USER_SIGNUP_SUCCESS",
  USER_SIGNUP_FAILED: "USER_SIGNUP_FAILED",

  HOME_REQUEST: "HOME_REQUEST",
  HOME_SUCCESS: "HOME_SUCCESS",
  HOME_FAILED: "HOME_FAILED",

  PROFILE_REQUEST: "PROFILE_REQUEST",
  PROFILE_SUCCESS: "PROFILE_SUCCESS",
  PROFILE_FAILED: "PROFILE_FAILED",

  PROFILE_UPDATE_REQUEST: "PROFILE_UPDATE_REQUEST",
  PROFILE_UPDATE_SUCCESS: "PROFILE_UPDATE_SUCCESS",
  PROFILE_UPDATE_FAILED: "PROFILE_UPDATE_FAILED",
};
